version: '3'
services:

  api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: docker-lumen
    ports:
      - 8080:80
    volumes:
      - ./../backend:/var/www/app
    links:
      - mysql
      - redis
      - phpmyadmin
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8000:80'
    networks:
      - app-network

  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
